security:
    password_hashers:
        # Use the User entity as your password hasher
        App\Entity\User: 'auto'

    providers:
        # Doctrine provider for fetching users from the database
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email  # Use "email" as the user identifier

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider

            # Enable form login for the main firewall
            form_login:
                login_path: app_login     # Route for the login form
                check_path: app_login # A separate route to handle login submissions
                default_target_path: homepage  # Redirect after login (optional)
                username_parameter: _email  # Field used to log in (email in this case)
                password_parameter: _password
                enable_csrf: true
                csrf_parameter: _csrf_token
                csrf_token_id: authenticate


            logout:
                path: app_logout
                target: homepage  # Redirect after logout (optional)

    access_control:
        # Allow anonymous access to the login page
        - { path: ^/login$, roles: PUBLIC_ACCESS }
        # Require authentication for all other pages
        - { path: ^/, roles: ROLE_USER }
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
